export enum Role {
  ADMIN = 'ADMIN', COORDINATOR = 'COORDINATOR', PANEL_CHAIR = 'PANEL_CHAIR',
  JUDGE = 'JUDGE', TEAM_REP = 'TEAM_REP', AUDITOR = 'AUDITOR',
}
export enum EventStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', COMPLETED = 'COMPLETED', ARCHIVED = 'ARCHIVED' }
export enum TeamStatus { DRAFT = 'DRAFT', SUBMITTED = 'SUBMITTED', ELIGIBLE = 'ELIGIBLE', SCHEDULED = 'SCHEDULED', JUDGED = 'JUDGED', COMPLETED = 'COMPLETED', DISQUALIFIED = 'DISQUALIFIED' }
export enum JudgeType { TECHNICAL = 'TECHNICAL', BUSINESS = 'BUSINESS', DOMAIN = 'DOMAIN', INNOVATION = 'INNOVATION', EXECUTIVE = 'EXECUTIVE' }
export enum JudgeStatus { ACTIVE = 'ACTIVE', UNAVAILABLE = 'UNAVAILABLE', WITHDRAWN = 'WITHDRAWN' }
export enum SessionStage { SCHEDULED = 'SCHEDULED', TEAM_CHECKED_IN = 'TEAM_CHECKED_IN', JUDGES_PRESENT = 'JUDGES_PRESENT', READY = 'READY', IN_PROGRESS = 'IN_PROGRESS', QA = 'QA', SCORING = 'SCORING', COMPLETED = 'COMPLETED', DELAYED = 'DELAYED', AT_RISK = 'AT_RISK', RESCHEDULED = 'RESCHEDULED', CANCELLED = 'CANCELLED', NO_SHOW = 'NO_SHOW' }
export enum ScorecardStatus { NOT_STARTED = 'NOT_STARTED', DRAFT = 'DRAFT', SUBMITTED = 'SUBMITTED', REOPENED = 'REOPENED', RESUBMITTED = 'RESUBMITTED', LOCKED = 'LOCKED' }
export enum SlotType { JUDGING = 'JUDGING', BREAK = 'BREAK', LUNCH = 'LUNCH', CEREMONY = 'CEREMONY', BLOCKED = 'BLOCKED' }
export enum ConflictSource { SELF_DECLARED = 'SELF_DECLARED', ADMIN_IMPOSED = 'ADMIN_IMPOSED' }
export enum ConflictStatus { ACTIVE = 'ACTIVE', RESOLVED = 'RESOLVED' }
export enum AuditAction { CREATE = 'CREATE', UPDATE = 'UPDATE', DELETE = 'DELETE' }
export enum RankingStatus { CALCULATING = 'CALCULATING', PROVISIONAL = 'PROVISIONAL', APPROVED = 'APPROVED', PUBLISHED = 'PUBLISHED' }
export enum PresentationMode { IN_PERSON = 'IN_PERSON', VIRTUAL = 'VIRTUAL' }
export enum ExpertiseLevel { PRIMARY = 'PRIMARY', SECONDARY = 'SECONDARY' }
export enum TrackStatus { ACTIVE = 'ACTIVE', ARCHIVED = 'ARCHIVED' }
export enum RoomStatus { ACTIVE = 'ACTIVE', UNAVAILABLE = 'UNAVAILABLE' }
export enum ScoringTemplateStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', LOCKED = 'LOCKED' }
